---
- name: Common system settings
  block:

  - name: Remove scaleway /etc/motd.head
    file:
      path: /etc/motd.head
      state: absent

  - name: Removing /etc/update.motd
    file:
      path: /etc/update-motd.d/{{ item }}
      state: absent
    with_items:
      - 50-scw
      - 50-motd-news

  when: ansible_distribution == "Ubuntu"
