---
# Kubernetes
kubernetes_apt_key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
kubernetes_apt_channel: main
kubernetes_release: xenial-unstable
# versions can be found here
kubernetes_version: v1.9.0-alpha.1
kubernetes_port: 6443

# Calico
# these will determine the number of pods you can run
# cirdr should be at least /16 https://kubernetes.io/docs/admin/kubeadm/
calico_cidr: 192.168.0.0/16
calico_manifest: http://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml
flannel_cidr: 10.244.0.0/16
flannel_manifest: https://raw.githubusercontent.com/coreos/flannel/v0.9.0/Documentation/kube-flannel.yml
#service_subnet: 10.66.0.0/12

# floating balanced ip for k8s api
api_floating_ip: 192.168.66.253
api_floating_mask: 24
api_floating_port: 6443
router_id: 66
